---
title: "try"
author: "Dorothy Bishop"
date: "26/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(DiagrammeR)
```




```{r makediag,echo=F}



a=23
b=45

grViz(diagram = "digraph flowchart {
  node [fontname = arial, shape = rectangle, color = grey, style = filled]
  tab1 [label = '@@1']
  tab2 [label = '@@2']
  tab3 [label = '@@3']
  
  tab1 -> tab2 -> tab3;
}
  
  [1]: paste0('Screening questions',':\\n', 'Aged 16-50; Hearing and vision;',':\\n','Native language; Neurological',':\\n', 'history; Developmental disorders;',':\\n', 'fMRI screening; Willingness to',':\\n','attend Session 2')
  [2]: paste0('Step 1: Online battery',':\\n','Demographic questionnaire',':\\n','Language proficiency measures',':\\n','Handedness/footedness/eyedness',':\\n','4 lateralisation tasks',':\\n','Planned N = 450',':\\n','Actual N = xxxx'  )  
  [3]: paste0('Step 2:   Functional TCD', ':\\n','At Oxford, Bangor, London',':\\n',' Lincoln, Lancaster, or UWA',':\\n','6 language tasks',':\\n','Planned N = 224',':\\n','Actual N = ',a+b)
  ")

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
